### ISSUE TITLE
Add a Remote Settings server to Merino's development docker-compose

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#168]
For local development and testing it would be useful to have an isolated Remote Settings environment to work with.

Experimenter has a similar set up, which can be seen [in its repository](https://github.com/mozilla/experimenter/blob/7276e262142d335d48b213e65715222976a796f6/docker-compose.yml#L95-L104).

The Kinto instance does not need all the features of the main Remote Settings. It only needs `kinto_attachments` and `kinto_changes` to be compatible with Merino.

This issue does not cover adding any content, automatically or manually, to the server. Documenting how to use it, such as the URLs used, should be covered though.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1315)
┆Epic: merino-milestone-1

**Comment by hackebrot** [comment]
Was this resolved via #215? 🤖

**Comment by mythmon** [comment]
Oops, it was.
