### ISSUE TITLE
RRA for Merino - Nov 2021

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#200]
This is a proxy for the RRA filed for Merino for November's tests and experiments.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1337)
┆Epic: merino-milestone-1

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Mark Reid when is this meeting?

**Comment by data-sync-user** [comment]
➤ Michael Cooper commented:

David Durst this should probably have the nosync label, right? Since it doesn’t involve code changes

**Comment by data-sync-user** [comment]
➤ Mark Reid commented:

David Durst the RRA is scheduled for tomorrow (Nov 4).

**Comment by ddurst** [comment]
Grrr.
