### ISSUE TITLE
Monitor the cache size and hit ratio

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#207]
We should be recording the metrics used for computing the following metrics:

* Suggestions cache hit ratio (this requires both cache hit and cache miss I guess)
* Suggestions cache size

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1354)
┆Epic: Operational real-time monitoring of business metrics

**Comment by Dexterp37** [comment]
Fixed by #208 . Will file a follow-up for the remaining item.
