### ISSUE TITLE
Missing location fields in logs filled with "none" string

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/merino#230]
I'm viewing nonprod logs flowing to BigQuery for the first time as part of https://mozilla-hub.atlassian.net/browse/SVCSE-138 and I'm noticing that many fields in the request log messages are filled with the literal string "none".

Do we know if this is intentional behavior of the application logic or of the underlying `tracing` library?

It's my expectation that rust `None` values would be represented in serialized JSON as `null` rather than string "none", or that the field would not appear in the schema at all.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1385)

**Comment by mythmon** [comment]
@jklukas can you share one of the log messages you're seeing, or share how to access those logs?

**Comment by jklukas** [comment]
The logs are locked down, but I will make a sample available to you.

**Comment by mythmon** [comment]
> The logs are locked down

excellent

>  I will make a sample available to you

I looked at the sample Jeff gave me, and it seems the only fields returning `"none"` are the location based fields. This was intention for compatibility with the adM API, but that's not relevant anymore. We can change this to report true `null`s.

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

Instead of replacing None values w/ null, merino now omits these fields entirely.

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

Already closed on the github side (failed to sync)
