### ISSUE TITLE
Tags from git branches other than main trigger deployments

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#240]
For the 0.4.2 release, I pushed a tagged commit to a branch to open a PR (as our release instructions say). I noticed that the process to deploy stage has already started, even though that PR has not been merged to the main branch. This skips some of the branch protections that we are supposed to have for deploys. We should fix this.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/CONSVC-1393)

**Comment by mythmon** [comment]
The new config doesn't fix this. Tags from non-main branches are still considered. Based on some research, it may not be possible to only read tags from a single branch.

**Comment by data-sync-user** [comment]
➤ Michael Cooper commented:

Re-opening, since the issue was not fixed as expected.

**Comment by data-sync-user** [comment]
➤ Michael Cooper commented:

This is just how CircleCI works. It does not give us tools to tell what branch a tag is on, and so we have to accept that things will deploy when we push tags. We have other security points along the deploy process, and we may not be using tags for much longer, so this isn't as big as an issue as it might be otherwise.
