### ISSUE TITLE
The “advertiser” data from the telemetry pings have the “adm” value instead of the sponsored or non sponsored advertiser

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-services/merino#245]
**[Affected Versions]:**
- Firefox Nightly 96.0a1 (Build ID: 20211124155224)
- Firefox Beta 95.0b11 (Build ID: 20211123190150)
- Firefox Release 94.0.2 (Build ID: 20211117154346)

**[Affected Platforms]:**
- Windows 10 x64
- macOS 10.15.7
- Ubuntu 20.04 x64

**[Prerequisites]:**
- Have the "browser.urlbar.merino.enabled" set to true.
- Have the "browser.urlbar.merino.endpointURL" set to "https://stage.merino.nonprod.cloudops.mozgcp.net/api/v1/suggest".
- Have the "browser.urlbar.quicksuggest.remoteSettings.enabled" set to "false".
- Have the "browser.urlbar.quicksuggest.dataCollection.enabled" set to "true"
- Have the "browser.ping-centre.log" set to "true".
- Have the "browser.search.region" set to "US".
- Have the browser console opened.

**[Steps to reproduce]:**
1. Open the latest Nightly/Beta build with the profile from prerequisites.
2. Open a New Tab page and type "ebay".
3. Click the Sponsored result displayed on the last position.
4. Observe the impression and click pings registered in the browser console.

**[Expected results]:**
- Both pings contain the “advertiser” data with “ebay” value. 

**[Actual results]:**
- Both pings contain the “advertiser” data with “adm” value. 

**[Notes]:**
- For the Remote Settings results the " the “advertiser” data registers the correct values:
1. “ebay” for the sponsored advertiser
2. “wikipedia” for the non sponsored advertiser
- Not sure if this issue is related to #242.
- Attached is a screen recording of the issue:

![advertiser](https://user-images.githubusercontent.com/26000308/143452849-4660018f-9ad1-4483-ab2f-74327b9e9216.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1397)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on the latest Beta 95.0b12 on Windows 10 x64, macOS 10.15.7 and Linux Mint 20 x64.
- The "advertiser" data from the telemetry pings have the correct value.

Based on this, we consider this issue as Verified - Fixed.

**Comment by data-sync-user** [comment]
➤ Nive Suresh commented:

This was resolved in GitHub
