### ISSUE TITLE
Fetch SuggestionProvider config from a URL provided in the system settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#294]
The static settings for Merino should list a URL that the suggestion provider dynamic settings can be loaded from. This URL should be fetched during the application startup and used to initialize the suggestion providers.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1522)
┆epic: Merino settings admin: Load admin settings from a remote system

**Comment by mythmon** [comment]
This as fixed as a part of #315.
