### ISSUE TITLE
Make search indexer schema for Wikipedia

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#304]
Choose a search engine system, such as Tantivy, ElasticSearch, or similar, and prepare a index schema that is suitable for searching Wikipedia content. The content to fill this schema with will come from [https://mozilla-hub.atlassian.net/browse/CONSVC-1513](https://mozilla-hub.atlassian.net/browse/CONSVC-1513|smart-link) eventually, but may come from other sources as a stop gap.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1512)
┆epic: Wikipedia local search provider

**Comment by mythmon** [comment]
Fixed by #329
