### ISSUE TITLE
Send the duration of the memory cache cleanup to metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#308]
Merino already measures the cache cleanup duration, but it only logs that information. We should also send it to metrics for the better observability.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1530)
┆epic: Merino: Ongoing reliability

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Adding notes here for  reference:

The memory cleanup task is this function here: https://github.com/mozilla-services/merino/blob/9cde6b317ba42c604b635ad103b96d72f3d4041b/merino-cache/src/memory.rs#L153 ( https://github.com/mozilla-services/merino/blob/9cde6b317ba42c604b635ad103b96d72f3d4041b/merino-cache/src/memory.rs#L153|smart-link ) 

 fn remove_expired_entries(&mut self) {

Related code block (from Nan and Mythmon) where another function records duration

https://github.com/mozilla-services/merino/blob/9cde6b317ba42c604b635ad103b96d72f3d4041b/merino-cache/src/memory.rs#L277-L281 ( https://github.com/mozilla-services/merino/blob/9cde6b317ba42c604b635ad103b96d72f3d4041b/merino-cache/src/memory.rs#L277-L281|smart-link ) 

:
https://github.com/mozilla-services/merino/blob/main/merino-cache/src/memory.rs#L179-L200 ( https://github.com/mozilla-services/merino/blob/main/merino-cache/src/memory.rs#L179-L200|smart-link ) 

        // Report finishing.
        let duration = Instant::now() - start;
        let removed_storage = count_before_storage - self.items.len_storage();
        let removed_pointers = count_before_pointers - self.items.len_pointers();
        tracing::info!(
            r#type = "cache.memory.remove-expired",
            ?duration,
            ?removed_pointers,
            ?removed_storage,
            "finished removing expired entries from cache"
        );

        self.metrics_client
            .gauge("cache.memory.storage-len", self.items.len_storage() as u64)
            .ok();
        self.metrics_client
            .gauge(
                "cache.memory.pointers-len",
                self.items.len_pointers() as u64,
            )
            .ok();
    }Goal: we want to send the duration value to StatsD metrics, like it does in line 191 (13 Jira).

currently, the duration is only logged on line 183, so also we want to call self.metrics_client.gauge(...) to send it to StatsD metrics

**Comment by jrconlin** [comment]
`metrics` also has a `MetricTimer`  that is started via `start_timer(label, tags)`. Timers are calculated and recorded when the owning metric falls out of scope (which can happen when the code exits a block, see the `Drop` impl for details). That might make things a bit easier.

**Comment by mythmon** [comment]
`MetricTimer` is restricted to recording times in milliseconds, since that is technically all that Statsd supports. In the example above the duration is being recorded with `time_micros_with_tags`, which is a part of a custom trait that I added for Merino. It records durations more precisely (as microseconds) and stores them in a histogram type instead of a timer type.

There isn't an equivalent to `MetricTimer` for microsecond resolution yet. Adding them would be nice, but perhaps out of Taddes's skill level right now.

**Comment by data-sync-user** [comment]
➤ Taddes Korris commented:

Task is resolved. See comments in GitHub to see entire history, but in essence, the Timed trait was pulled in to implement the time method, so the StatsdClient could handle this metric value. Some refactoring in the unit tests was required to accommodate the new metric and because its data type was not a gauge. Also, the try_iter() method was implemented to prevent blocking when running the tests, as the take() method was removed.
