### ISSUE TITLE
Error: linking with `cc` failed

### ISSUE THREAD

**Issue by jklukas** [mozilla-services/merino#322]
When trying to compile this project for the first time and run tests, I ran into some linking error.

I ran the documented instructions:

```
$ docker-compose -f dev/docker-compose.yaml up -d
$ cargo test
```

The docker-compose configuration launched successfully, but `cargo test` failed with:

```
<snip>

   Compiling merino-adm v0.5.1 (/Users/jklukas/Code/merino/merino-adm)
   Compiling merino-web v0.5.1 (/Users/jklukas/Code/merino/merino-web)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/Users/jklukas/Code/merino/target/debug/deps/merino_settings-54cf418990a9e503.1509bqjy37dfkjbp.rcgu.o"

<snip>

  = note: 0  0x10286c224  __assert_rtn + 128
          1  0x1028717e8  ld::tool::OutputFile::addressAndTarget(ld::Internal const&, ld::Fixup const*, ld::Atom const**) (.cold.1) + 0
          2  0x1027ab104  ld::tool::OutputFile::addressOf(ld::Internal const&, ld::Fixup const*, ld::Atom const**) + 252
          3  0x1027acdfc  ld::tool::OutputFile::applyFixUps(ld::Internal&, unsigned long long, ld::Atom const*, unsigned char*) + 4004
          4  0x1027b1540  ld::tool::OutputFile::writeAtoms(ld::Internal&, unsigned char*) + 356
          5  0x1027a8fa4  ld::tool::OutputFile::writeOutputFile(ld::Internal&) + 408
          6  0x1027a1adc  ld::tool::OutputFile::write(ld::Internal&) + 216
          7  0x10272f1d8  main + 584
          A linker snapshot was created at:
          	/tmp/merino_settings-54cf418990a9e503-2022-00-26-190755.ld-snapshot
          ld: Assertion failed: (_mode == modeFinalAddress), function finalAddress, file ld.hpp, line 1190.
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `merino-settings` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I'm running on a new M1 Macbook Pro which could well be related. Do we know of anybody who has been doing development on merino using an Apple Silicon machine?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1589)

**Comment by mythmon** [comment]
Clearing the build cache is simple: `cargo clean`. Often however Rust will automatically store it's built artifacts in different places for different architectures, so you may not even need to do that. As for running rust in Rosetta mode, I can't offer any suggestions there.

**Comment by pjenvey** [comment]
This sounds like this issue https://github.com/rust-lang/rust/issues/90342

It offers a workaround: `cargo clean`, then retry again w/ `export MACOSX_DEPLOYMENT_TARGET=10.7`.

Feel free to reopen this if that doesn't solve it.
