### ISSUE TITLE
Ensure that all `reqwest` calls have `timeout` and `connect_timeout` specified

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#342]
A recent error in Contile showed that a change had been made to the default behavior of `reqwest` clients. `.timeout()` and `.connect_timeout()` default values had been removed. These are important values for efficient server operation and should be set via a configuration.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1634)

**Comment by ddurst** [comment]
Grr
