### ISSUE TITLE
Use Actix Web to parse Accept-Language header

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/merino#90]
As part of CONSVC-107, we wrote code to manually parse the `Accept-Language` headers of incoming requests. Instead, let's use [Actix Web](https://docs.rs/actix-web/3.3.2/actix_web/http/header/struct.AcceptLanguage.html) to parse the header. An example of this on syncstorage can be found [here](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/extractors.rs#L116).

Benefits to this approach:

* Reusing code in a widely-used library is less error-prone than maintaining the parsing code ourselves
* If the format for the `Accept-Language` header is ever changed, we would (hopefully) be able to rely on upstream libraries to implemented those changes (as opposed to having to keep up with such changes ourselves)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1183)

**Comment by Dexterp37** [comment]
This is blocked on actix/actix-web#2434

**Comment by data-sync-user** [comment]
➤ Alessio Placitelli commented:

Moved this to backlog as it’s blocked on upstream, actix-web fixes.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Looks like this is now unblocked. Could we move this to ready?
